name = "mica"
license = "GPLv3"
licenselink = ""
description = "A very lightweight retro theme for Hugo!"
homepage = "https://github.com/k3rs3d/mica"
tags = ["minimalist", "retro", "blog"]
features = ["blog"]
min_version = 0.90

[author]
  name = "Kersed"
  homepage = "https://kersed.net"
